import "./App.css";
import { useEffect, useRef, useState } from "react";
import { WordCloud } from "@antv/g2plot";

const chartData = [
  { name: "发展", value: 91 },
  { name: "建设", value: 87 },
  { name: "推进", value: 80 },
  { name: "西藏", value: 71 },
  { name: "全面", value: 58 },
  { name: "社会", value: 53 },
  { name: "生态", value: 45 },
  { name: "工作", value: 37 },
  { name: "人民", value: 37 },
  { name: "实施", value: 36 },
  { name: "民族", value: 36 },
  { name: "经济", value: 35 },
  { name: "产业", value: 33 },
  { name: "国家", value: 30 },
  { name: "群众", value: 28 },
  { name: "边境", value: 28 },
  { name: "工程", value: 26 },
  { name: "改革", value: 24 },
  { name: "团结", value: 24 },
  { name: "全国", value: 23 },
  { name: "体系", value: 23 },
  { name: "标准", value: 23 },
  { name: "代表", value: 22 },
  { name: "稳定", value: 22 },
  { name: "中央", value: 21 },
  { name: "企业", value: 21 },
  { name: "地区", value: 20 },
  { name: "自治区", value: 19 },
  { name: "保护", value: 19 },
  { name: "城镇", value: 18 },
  { name: "重点", value: 17 },
  { name: "生活", value: 16 },
  { name: "城乡", value: 16 },
  { name: "制度", value: 16 },
  { name: "设施", value: 16 },
  { name: "规划", value: 15 },
  { name: "基础", value: 15 },
  { name: "高原", value: 15 },
  { name: "新时代", value: 14 },
  { name: "文化", value: 14 },
  { name: "乡村", value: 14 },
  { name: "能力", value: 14 },
  { name: "旅游", value: 14 },
  { name: "投资", value: 14 },
  { name: "中国", value: 13 },
  { name: "宗教", value: 13 },
  { name: "铁路", value: 13 },
  { name: "绿色", value: 13 },
  { name: "特色", value: 13 },
  { name: "管理", value: 13 },
  { name: "基地", value: 13 },
  { name: "目标", value: 12 },
  { name: "意识", value: 12 },
  { name: "质量", value: 12 },
  { name: "项目", value: 12 },
  { name: "能源", value: 12 },
  { name: "中华 ", value: 12 },
  { name: "合作 ", value: 12 },
  { name: "人口 ", value: 11 },
  { name: "居民 ", value: 11 },
  { name: "环境 ", value: 11 },
  { name: "斗争 ", value: 11 },
  { name: "收入 ", value: 11 },
  { name: "科技 ", value: 11 },
  { name: "创建 ", value: 11 },
  { name: "监督 ", value: 11 },
  { name: "开发 ", value: 11 },
  { name: "人均 ", value: 10 },
  { name: "习近平 ", value: 10 },
  { name: "青藏 ", value: 10 },
  { name: "机场 ", value: 10 },
  { name: "战略 ", value: 10 },
  { name: "机制 ", value: 10 },
  { name: "公路 ", value: 10 },
  { name: "自然 ", value: 10 },
  { name: "资源 ", value: 10 },
  { name: "国际 ", value: 10 },
  { name: "支持 ", value: 10 },
  { name: "生产 ", value: 10 },
  { name: "技术 ", value: 10 },
  { name: "历史 ", value: 10 },
  { name: "工业 ", value: 10 },
  { name: "农牧民 ", value: 9 },
  { name: "全区 ", value: 9 },
  { name: "共同体 ", value: 9 },
  { name: "青稞 ", value: 9 },
  { name: "农村 ", value: 9 },
  { name: "资产 ", value: 9 },
  { name: "聚力 ", value: 9 },
  { name: "政策 ", value: 9 },
  { name: "活动 ", value: 9 },
  { name: "格局 ", value: 9 },
  { name: "改造 ", value: 9 },
  { name: "系统 ", value: 9 },
  { name: "分裂 ", value: 9 },
  { name: "产品 ", value: 9 },
  { name: "援藏 ", value: 9 },
  { name: "污染 ", value: 9 },
  { name: "市场 ", value: 9 },
  { name: "日喀则 ", value: 8 },
  { name: "民生 ", value: 8 },
  { name: "面积 ", value: 8 },
  { name: "精神 ", value: 8 },
  { name: "城市 ", value: 8 },
  { name: "10 % ", value: 8 },
  { name: "电力 ", value: 8 },
  { name: "单位 ", value: 8 },
  { name: "政务 ", value: 8 },
  { name: "思想 ", value: 8 },
  { name: "水平 ", value: 8 },
  { name: "口岸 ", value: 8 },
  { name: "区内 ", value: 8 },
  { name: "医疗 ", value: 8 },
  { name: "人员 ", value: 7 },
  { name: "国内 ", value: 7 },
  { name: "领导 ", value: 7 },
  { name: "平台 ", value: 7 },
  { name: "人才 ", value: 7 },
  { name: "区域 ", value: 7 },
  { name: "产量 ", value: 7 },
  { name: "总体 ", value: 7 },
  { name: "电网 ", value: 7 },
  { name: "应急 ", value: 7 },
  { name: "贫困 ", value: 6 },
  { name: "国务院 ", value: 6 },
  { name: "卫生 ", value: 6 },
  { name: "那曲 ", value: 6 },
  { name: "林芝 ", value: 6 },
  { name: "总书记 ", value: 6 },
  { name: "成效 ", value: 6 },
  { name: "债务 ", value: 6 },
  { name: "99 % ", value: 6 },
  { name: "力度 ", value: 6 },
  { name: "专项 ", value: 6 },
  { name: "大局 ", value: 6 },
  { name: "作用 ", value: 6 },
  { name: "措施 ", value: 6 },
  { name: "成果 ", value: 6 },
  { name: "科学 ", value: 6 },
  { name: "优势 ", value: 6 },
  { name: "基层 ", value: 6 },
  { name: "阶段 ", value: 6 },
  { name: "水电 ", value: 6 },
  { name: "数字 ", value: 6 },
  { name: "政协 ", value: 5 },
  { name: "年均 ", value: 5 },
  { name: "雅鲁藏布江 ", value: 5 },
  { name: "努力 ", value: 5 },
  { name: "金沙江 ", value: 5 },
  { name: "佛教 ", value: 5 },
  { name: "央企 ", value: 5 },
  { name: "十三五 ", value: 5 },
  { name: "委员 ", value: 5 },
  { name: "祖国 ", value: 5 },
  { name: "动态 ", value: 5 },
  { name: "机构 ", value: 5 },
  { name: "干部 ", value: 5 },
  { name: "牦牛 ", value: 5 },
  { name: "建制 ", value: 5 },
  { name: "技能 ", value: 5 },
  { name: "物流 ", value: 5 },
  { name: "生物 ", value: 5 },
  { name: "布局 ", value: 5 },
  { name: "网络 ", value: 5 },
  { name: "功能 ", value: 5 },
  { name: "品牌 ", value: 5 },
  { name: "人大 ", value: 4 },
  { name: "国企 ", value: 4 },
  { name: "高校 ", value: 4 },
  { name: "吉隆 ", value: 4 },
  { name: "南亚 ", value: 4 },
  { name: "2020 年 ", value: 4 },
  { name: "昌都 ", value: 4 },
  { name: "内地 ", value: 4 },
  { name: "远景 ", value: 4 },
  { name: "高新 ", value: 4 },
  { name: "阿里 ", value: 4 },
  { name: "疫情 ", value: 4 },
  { name: "隐性 ", value: 4 },
  { name: "前所未有 ", value: 3 },
  { name: "农畜 ", value: 3 },
  { name: "商贸 ", value: 3 },
  { name: "长治久安 ", value: 3 },
  { name: "军地 ", value: 3 },
  { name: "山南 ", value: 3 },
  { name: "大会 ", value: 3 },
  { name: "万户 ", value: 3 },
  { name: "网上 ", value: 3 },
  { name: "全年 ", value: 3 },
  { name: "报告 ", value: 2 },
  { name: "跨喜马拉雅 ", value: 2 },
  { name: "改扩建 ", value: 2 },
  { name: "孕产妇 ", value: 2 },
  { name: "邦达 ", value: 2 },
  { name: "拉林 ", value: 2 },
  { name: "珠峰 ", value: 2 },
  { name: "深入人心 ", value: 2 },
  { name: "羌塘 ", value: 2 },
  { name: "五大 ", value: 2 },
  { name: "澜沧江 ", value: 2 },
  { name: "进出口 ", value: 2 },
  { name: "区管 ", value: 2 },
  { name: "河湖 ", value: 2 },
  { name: "4 % ", value: 2 },
  { name: "纲要 ", value: 2 },
  { name: "齐扎拉 ", value: 1 },
  { name: "会议 ", value: 1 },
  { name: "金瓶掣签 ", value: 1 },
  { name: "主席 ", value: 1 },
  { name: "毛泽东 ", value: 1 },
  { name: "满怀信心 ", value: 1 },
  { name: "欢欣鼓舞 ", value: 1 },
  { name: "重特大 ", value: 1 },
  { name: "恰央 ", value: 1 },
  { name: "实惠 ", value: 1 },
  { name: "安委会 ", value: 1 },
  { name: "三公 ", value: 1 },
  { name: "只争朝夕 ", value: 1 },
  { name: "五中全会 ", value: 1 },
  { name: "二中 ", value: 1 },
  { name: "三中 ", value: 1 },
  { name: "扶智 ", value: 1 },
  { name: "四中 ", value: 1 },
  { name: "藏语 ", value: 1 },
  { name: "十九大 ", value: 1 },
  { name: "尼务实 ", value: 1 },
  { name: "三大 ", value: 1 },
  { name: "本外币 ", value: 1 },
  { name: "中共 ", value: 1 },
  { name: "无私支援 ", value: 1 },
  { name: "教职员工 ", value: 1 },
  { name: "移风易俗 ", value: 1 },
  { name: "风清气正 ", value: 1 },
  { name: "湘河 ", value: 1 },
  { name: "十佳 ", value: 1 },
  { name: "雅砻 ", value: 1 },
  { name: "三科 ", value: 1 },
  { name: "四位一体 ", value: 1 },
  { name: "直管 ", value: 1 },
  { name: "农技 ", value: 1 },
  { name: "入院 ", value: 1 },
  { name: "财税 ", value: 1 },
  { name: "三岩 ", value: 1 },
  { name: "七大 ", value: 1 },
  { name: "广电 ", value: 1 },
  { name: "农电 ", value: 1 },
  { name: "三州 ", value: 1 },
  { name: "千分之八 ", value: 1 },
  { name: "德智体美劳 ", value: 1 },
  { name: "无树户 ", value: 1 },
  { name: "复兴号 ", value: 1 },
  { name: "四旁 ", value: 1 },
  { name: "众志成城 ", value: 1 },
  { name: "民爆 ", value: 1 },
  { name: "医保 ", value: 1 },
  { name: "滇藏 ", value: 1 },
  { name: "成渝 ", value: 1 },
  { name: "堰塞湖 ", value: 1 },
  { name: "环保 ", value: 1 },
  { name: "双拥 ", value: 1 },
  { name: "大中小学 ", value: 1 },
  { name: "农科 ", value: 1 },
  { name: "金桥 ", value: 1 },
  { name: "印度 ", value: 1 },
  { name: "监委 ", value: 1 },
  { name: "京藏 ", value: 1 },
  { name: "昆莎 ", value: 1 },
  { name: "六保 ", value: 1 },
  { name: "尼泊尔 ", value: 1 },
  { name: "利民 ", value: 1 },
  { name: "拉洛 ", value: 1 },
  { name: "政法 ", value: 1 },
  { name: "普兰 ", value: 1 },
  { name: "产教 ", value: 1 },
  { name: "国资 ", value: 1 },
  { name: "普法 ", value: 1 },
  { name: "五有 ", value: 1 },
  { name: "惠企 ", value: 1 },
  { name: "扎西德勒 ", value: 1 },
  { name: "天堑 ", value: 1 },
  { name: "建成区 ", value: 1 },
  { name: "及区 ", value: 1 },
  { name: "大唐 ", value: 1 },
  { name: "芒康 ", value: 1 },
  { name: "天湖 ", value: 1 },
  { name: "贡嘎 ", value: 1 },
  { name: "波密 ", value: 1 },
  { name: "双城 ", value: 1 },
  { name: "江源 ", value: 1 },
  { name: "两江 ", value: 1 },
  { name: "亚东 ", value: 1 },
  { name: "陈塘 ", value: 1 },
  { name: "达峰 ", value: 1 },
  { name: "枫桥 ", value: 1 },
  { name: "里孜 ", value: 1 },
  { name: "小镇 ", value: 1 },
  { name: "感党恩 ", value: 1 },
];

const App = () => {
  const ref = useRef(null);
  const [data, setData] = useState(chartData);
  const instance = useRef();

  // useEffect(() => {
  //   fetch(
  //     "https://gw.alipayobjects.com/os/antvdemo/assets/data/antv-keywords.json"
  //   )
  //     .then((res) => res.json())
  //     .then((data) => {
  //       setData(data);
  //     });
  // }, []);

  useEffect(() => {
    if (data) {
      if (instance.current) {
        instance.current.destroy();
      }
      const wordCloud = new WordCloud(ref.current, {
        data,
        width: 1920,
        height: 900,
        wordField: "name",
        weightField: "value",
        colorField: "name",
        wordStyle: {
          fontFamily: "Verdana",
          fontSize: [8, 32],
          rotation: 0,
        },
        // 返回值设置成一个 [0, 1) 区间内的值，
        // 可以让每次渲染的位置相同（前提是每次的宽高一致）。
        random: () => 0.5,
      });

      wordCloud.render();
      instance.current = wordCloud;
    }
  }, [data]);

  return (
    <div className="App">
      <div ref={ref}></div>
      <button className="refresh" onClick={() => setData([...data])}>
        refresh
      </button>
    </div>
  );
};

export default App;
