import { themeColors } from "@/common/global/themes";

export default {
  chartTheme: {
    visible: true,
    label: "图表风格",
    value: "default",
    componentName: "Select",
    itemKey: "chartTheme",
    type: "theme",
    action: "setChartTheme",
    options: [
      { value: "default", label: "默认风格" },
      { value: "dark", label: "深色主题" },
    ],
  },
  colorTheme: {
    visible: true,
    label: "颜色主题",
    value: "theme1",
    componentName: "SelectTheme",
    itemKey: "colorTheme",
    type: "theme",
    action: "setColorTheme",
    options: [
      { value: "theme1", label: "主题色1" },
      { value: "theme2", label: "主题色2" },
      { value: "theme3", label: "主题色3" },
    ],
  },
  colors: {
    visible: true,
    label: "编辑颜色",
    value: themeColors.theme1,
    componentName: "ColorEdit",
    itemKey: "colors",
    type: "theme",
    action: "setColors",
    origin: themeColors.theme1,
  },
  textColor: {
    visible: true,
    label: "图表文字颜色",
    value: "rgba(0, 0, 0, 1)",
    componentName: "Color",
    itemKey: "textColor",
    type: "theme",
    action: "setTextColor",
  },
  bgColor: {
    visible: true,
    label: "背景颜色",
    value: "rgba(255, 255, 255, 1)",
    componentName: "Color",
    itemKey: "bgColor",
    type: "theme",
    action: "setBgColor",
  },
  // bgImage: {
  //   visible: true,
  //   label: "背景图片",
  //   value: "",
  //   componentName: "Upload",
  //   itemKey: "bgImage",
  //   type: "theme",
  //   action: "setBgImage",
  // },
};
