export const subList = [
  {
    id: 1,
    userId: "xhs_chenweichao",
    typeId: 0,
    subTypeId: 0,
    subId: 0,
    info: null,
    updateTime: 1602472533000,
  },
  {
    id: 2,
    userId: "xhs_chenweichao",
    typeId: 0,
    subTypeId: 1,
    subId: 1,
    info: null,
    updateTime: 1602472536000,
  },
  {
    id: 3,
    userId: "xhs_chenweichao",
    typeId: 0,
    subTypeId: 1,
    subId: 0,
    info: null,
    updateTime: 1602472541000,
  },
  {
    id: 4,
    userId: "xhs_chenweichao",
    typeId: 0,
    subTypeId: 1,
    subId: 0,
    info: null,
    updateTime: 1602472538000,
  },
  {
    id: 5,
    userId: "xhs_chenweichao",
    typeId: 0,
    subTypeId: 2,
    subId: 0,
    info: "websitename",
    updateTime: 1602472543000,
  },
  {
    id: 6,
    userId: "xhs_chenweichao",
    typeId: 0,
    subTypeId: 2,
    subId: 1,
    info: "twitter-author",
    updateTime: 1602472546000,
  },
];

export const configList = {
  locationList: [
    { value: "China", key: "0" },
    { value: "Canada", key: "1" },
    { value: "Europe", key: "2" },
    { value: "Mexico", key: "3" },
    { value: "US", key: "4" },
    { value: "Asia", key: "5" },
  ],
  topicList: [
    { value: "cultrue", key: "0" },
    { value: "business", key: "1" },
    { value: "crime", key: "2" },
    { value: "education", key: "3" },
    { value: "entertainment", key: "4" },
    { value: "health", key: "5" },
    { value: "science", key: "7" },
    { value: "sports", key: "8" },
    { value: "tech", key: "9" },
    { value: "worldnews", key: "10" },
  ],
  websiteList: [
    "breitbart",
    "cnn",
    "fox",
    "npr",
    "ap",
    "reuters",
    "nbc",
    "politico",
    "abc",
    "atlantic",
    "guardian",
    "york",
    "post",
    "usa",
    "boston",
    "angeles",
    "washington",
    "chicago",
  ],
};
