export const defaultMasks = [
  { key: '0', name: '0', image: './data/images/0.png' }, 
  { key: '1', name: '1', image: './data/images/1.png' }, 
  { key: '2', name: '2', image: './data/images/2.png' }, 
  { key: '3', name: '3', image: './data/images/3.png' }, 
  { key: '4', name: '4', image: './data/images/4.png' },  
  { key: '5', name: '5', image: './data/images/5.png' }, 
  { key: '6', name: '6', image: './data/images/6.png' }, 
  { key: '7', name: '7', image: './data/images/7.png' }, 
  { key: '8', name: '8', image: './data/images/8.png' }, 
  { key: '9', name: '9', image: './data/images/9.png' }, 
  { key: '@', name: '@', image: './data/images/@.png' }, 
  { key: 'heart', name: '心形', image: './data/images/heart.png' }, 
  { key: 'flag', name: '国旗', image: './data/images/flag.png' }, 
  { key: 'tree', name: '树', image: './data/images/tree.png' }, 
  { key: 'chicken', name: '鸡', image: './data/images/chicken.png' }, 
  { key: 'fish', name: '鱼', image: './data/images/fish.png' }, 
  { key: 'rabbit', name: '兔兔', image: './data/images/rabbit.png' }, 
  { key: 'baboon', name: '狒狒', image: './data/images/baboon.png' }, 
  { key: 'monkey', name: '猴子', image: './data/images/monkey.png' }, 
  { key: 'lion', name: '狮子', image: './data/images/lion.png' }, 
  { key: 'polarbear', name: '北极熊', image: './data/images/polarbear.png' }, 
  { key: 'tortoise', name: '乌龟', image: './data/images/tortoise.png' }, 
  { key: 'book', name: '书', image: './data/images/book.png' },
  { key: 'computer', name: '电脑', image: './data/images/computer.png' },
  { key: 'robot', name: '机器人', image: './data/images/robot.png' }
]